CREATE DATABASE IF NOT EXISTS farmmart CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE farmmart;
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  firebase_uid VARCHAR(128) NOT NULL,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NULL,
  role ENUM('BUYER','SELLER','ADMIN') NOT NULL DEFAULT 'BUYER',
  avatar_url TEXT NULL,
  address TEXT NULL,
  state VARCHAR(100) NULL,
  city VARCHAR(100) NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_firebase_uid (firebase_uid),
  UNIQUE KEY uq_users_email (email),
  INDEX idx_users_role (role),
  INDEX idx_users_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS animals (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  name VARCHAR(200) NOT NULL,
  category ENUM('CATTLE','GOAT','SHEEP','PIG','POULTRY','RABBIT','HORSE','OTHER') NOT NULL,
  breed VARCHAR(150) NULL,
  age INT NULL COMMENT 'Age in months',
  weight DECIMAL(8,2) NULL COMMENT 'Weight in kg',
  price DECIMAL(12,2) NOT NULL,
  description TEXT NULL,
  images JSON NOT NULL COMMENT 'Array of Cloudinary URLs',
  status ENUM('AVAILABLE','SOLD','RESERVED') NOT NULL DEFAULT 'AVAILABLE',
  location VARCHAR(200) NULL,
  state VARCHAR(100) NULL,
  is_negotiable TINYINT(1) NOT NULL DEFAULT 0,
  view_count INT NOT NULL DEFAULT 0,
  seller_id VARCHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_animals_category (category),
  INDEX idx_animals_status (status),
  INDEX idx_animals_seller_id (seller_id),
  INDEX idx_animals_state (state),
  INDEX idx_animals_price (price),
  INDEX idx_animals_created_at (created_at),
  FULLTEXT INDEX ft_animals_search (name, breed, description),
  CONSTRAINT fk_animals_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS cart (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  user_id VARCHAR(36) NOT NULL,
  animal_id VARCHAR(36) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cart_user_animal (user_id, animal_id),
  INDEX idx_cart_user_id (user_id),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cart_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  buyer_id VARCHAR(36) NOT NULL,
  animal_id VARCHAR(36) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  status ENUM('PENDING','PAID','CANCELLED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  paystack_ref VARCHAR(200) NOT NULL,
  paystack_channel VARCHAR(50) NULL COMMENT 'card, bank, ussd, etc.',
  delivery_address TEXT NULL,
  delivery_state VARCHAR(100) NULL,
  delivery_city VARCHAR(100) NULL,
  notes TEXT NULL,
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_paystack_ref (paystack_ref),
  INDEX idx_orders_buyer_id (buyer_id),
  INDEX idx_orders_animal_id (animal_id),
  INDEX idx_orders_status (status),
  INDEX idx_orders_created_at (created_at),
  CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_orders_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS inquiries (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  sender_id VARCHAR(36) NOT NULL,
  receiver_id VARCHAR(36) NOT NULL,
  animal_id VARCHAR(36) NOT NULL,
  message TEXT NOT NULL,
  status ENUM('UNREAD','READ','REPLIED') NOT NULL DEFAULT 'UNREAD',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_inquiries_receiver_id (receiver_id),
  INDEX idx_inquiries_sender_id (sender_id),
  INDEX idx_inquiries_animal_id (animal_id),
  INDEX idx_inquiries_status (status),
  CONSTRAINT fk_inquiries_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_inquiries_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_inquiries_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS reviews (
  id VARCHAR(36) NOT NULL DEFAULT (UUID()),
  user_id VARCHAR(36) NOT NULL,
  animal_id VARCHAR(36) NOT NULL,
  rating TINYINT NOT NULL COMMENT '1 to 5',
  comment TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_reviews_user_animal (user_id, animal_id),
  INDEX idx_reviews_animal_id (animal_id),
  INDEX idx_reviews_rating (rating),
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_reviews_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
